.eslintrc.json, src/app/api/auth/[...nextauth]/authOptions.ts, src/app/api/auth/[...nextauth]/route.ts, src/app/create/list/page.tsx, src/types/next-auth.d.ts, src/utils/strapi.ts, tsconfig.json
- カードと作成者との結び付けがリレーションでできて嬉しい
- 後々Google以外でログインできるようにすることになったとしても多分安全
- 環境変数ページにセットアップ手順追加してるので確認お願いします
=> ユーザー情報をStrapiで管理する

src/layouts/EditCard/Edit/index.tsx
- 環境によってリンクが切れる
- 数が多いと左右にはみ出す
=> スタンプ選択UIの機能上の不具合を修正する

src/layouts/List/Header/index.css.ts, src/layouts/List/Header/index.tsx
- 郵便アイコンの数字の削除
- スクロールでtabの方を固定
=> fix Header

src/components/Print/index.tsx, src/utils/print.ts
- 仮実装だと任意のリクエストの踏み台にされえたのでどうにかする
=> テスト用の記述を整理

src/components/Card/Renderer/index.tsx, src/components/Card/index.css.ts, src/components/Card/index.tsx, src/layouts/Detail/index.tsx, src/layouts/EditCard/index.css.ts, src/layouts/EditCard/index.tsx, src/layouts/List/index.tsx, src/layouts/ReceivedDetail/index.tsx, src/layouts/Shared/index.tsx, src/utils/strapi/card.ts
- 先に https://github.com/diawel/akeome-link-cms/pull/16 を取り込む必要がある
- UIは仮
- `background-image` は、出力時に解像度が落ちるため使っていない
=> カードの背景変更機能

src/app/layout.tsx, src/layouts/EditCard/Edit/index.tsx, src/utils/strapi/sticker.ts
先にこっちを取り込む
https://github.com/diawel/akeome-link-cms/pull/27
- 過去/現行の区分に対応する
- 件数制限をなくす
=> ステッカー周りの調整

src/components/Card/Renderer/index.css.ts, src/components/Card/Renderer/index.tsx
=> Rendererを直す

src/layouts/DraftDetail/index.tsx
- 下書きページのコピーボタンでつづきから編集なのに, コピーして編集になっていたのを修正
=> fix draft text

src/layouts/EditCard/Setting/index.css.ts
カード作成画面のタイトル読み込み中のデザインをわかりやすくする
=> タイトル入力欄がdisableなのをわかりやすくする

IPA_Font_License_Agreement_v1.0.txt, src/app/api/og/route.tsx
- フォントの読み込み
- OGP画像で名前のフォントを変更
=>  OGP画像で名前のフォントを変更する

src/app/create/detail/[id]/page.tsx, src/app/create/edit/[id]/layout.tsx, src/app/create/new/[id]/page.tsx, src/app/create/new/page.tsx, src/app/layout.tsx, src/app/share/[id]/page.tsx, src/components/LoginButton/Dialog/index.css.ts, src/components/LoginButton/Dialog/index.tsx, src/components/LoginButton/LoginDialogProvider.tsx, src/components/LoginButton/index.tsx, src/layouts/List/Created/index.tsx, src/layouts/List/Received/index.tsx, src/layouts/List/index.tsx, src/layouts/Post/index.tsx, src/layouts/Shared/index.tsx, src/layouts/Top/index.css.ts, src/layouts/Top/index.tsx, src/utils/strapi/card.ts, src/utils/strapi/strapiImage.ts
- LINEやInstagramなどのアプリ内ブラウザでログインすると `403: disallowed_useragent` になる
- [ Googleのポリシー](https://developers.google.com/identity/protocols/oauth2/policies#browsers)によるもの
- 主要なブラウザーについてとりあえず直す
=> アプリ内ブラウザでログインしようとするとエラーになる問題への対応

src/layouts/EditCard/Setting/index.css.ts, src/layouts/EditCard/Setting/index.tsx
速達機能が使える期間と、速達を使わずに年賀状が年内に届く期間は同じ
=> 速達機能を1月のみ使えるようにする

src/app/layout.tsx
Reverts diawel/akeome-link#105
=> Revert "メンテナンス画面"

src/app/layout.tsx, src/components/LoginButton/Dialog/index.css.ts, src/layouts/pc/Left/index.tsx
=> PCレイアウトのログインボタンをLoginButtonに置き換える

src/app/layout.css.ts
=> [Hotfix] ipad noise texture

src/utils/strapi/card.ts, src/utils/strapi/receivedCard.ts, src/utils/strapi/sticker.ts
=> Feature stiker order

src/layouts/Share/Qr/index.css.ts, src/layouts/Share/Qr/index.tsx
- 縦幅が短い端末で埋まらないようにする
- 名前が正しく省略されるようにする
=> QRコード画面のCSSを改善する

src/layouts/Share/Qr/index.css.ts
=> SafariでQRが崩れないようにする

src/layouts/EditCard/Meta/index.tsx, src/layouts/EditCard/Setting/Meta/index.tsx
=> 編集画面のボタンのラベルを変更する

src/app/layout.tsx, src/middleware.ts
=> Feature maintenance mode
